---
Title: Cardiorespiratory Fitness and Morbidity and Mortality in Patients with Non-Small Cell Lung Cancer: A Prospective Study with Propensity Score Weighting
---



```{r}
##############################################################
# Hypothesis and the variables of the study
##############################################################
# Hypothesis: A lower cardiorespiratory fitness is associated with higher risk of perioperative complication and long-term all-cause mortality in operable patients with early-stage non-small-cell lung cancer


## Predictor: Cardiorespiratory fitness ##
# Continuous variable: CRF_continuous
# Categorical variable: CRF_binary


## Outcomes: the name in the manuscript, the name in the dataset, variable type ##
# Outcome 1: Mortality, Mortality, Categorical variable  (the date of event: Mortality_time_to_event)
# Outcome 2: The composite of perioperative complications, Composite_complications, Categorical variable
# Outcome 2.1: Technical-related complication, Technical_complication, Categorical variable
# Outcome 2.2: Pulmonary complication, Pulmonary_complication, Categorical variable
# Outcome 2.3: Cardiovascular complication, Cardiovascular_complication, Categorical variable


## Covariates: the name in the dataset, variable type ##
# Sex: Sex, Categorical variable
# Age: Age, Continuous variable
# Body mass index: BMI, Continuous variable
# Smoking ever: Smoking_ever, Categorical variable
# Hypertension: Hypertension, Categorical variable
# Dyslipidemia: Dyslipidemia, Categorical variable
# Diabetes mellitus: Diabetes, Categorical variable
# Coronary artery disease: Coronary_artery_disease, Categorical variable
# Histology: Histology, Categorical variable
# Type of lung resection: Type_of_lung_resection, Categorical variable
# Clinical stage: Clinical_stage, Categorical variable

```



```{r}

##############################################################
# To install the needed packages 
##############################################################
library("pROC")
library("PSweight")
library("survey")
library("tableone")
library("fmsb")
library("survival")
library("EValue")
library("boot")
library("cobalt")
library("rms")
library("survminer")

```



```{r}

##############################################################
# To read in data
##############################################################
setwd("working_directory")
data <- read.csv("dataset.csv",na=c("-"))
data_na_omit <- na.omit(data)

```



```{r}

#######################################################################################################
#  Receiver Operating Characteristic (ROC) curve analysis and optimal cut-off value identification
#######################################################################################################
# Reference: Xavier Robin, Natacha Turck, Alexandre Hainard, Natalia Tiberti, Frédérique Lisacek, Jean-Charles Sanchez, Markus Müller，Stefan Siegert, Matthias Doering, Zane Billings (2021). pROC: Display and Analyze ROC Curves-Processing in R. R package version 3.5-5. https://cran.r-project.org/web/packages/pROC

## ROC curve for the outcome of Mortality
rocobj_outcome1 <- pROC::roc(Mortality~CRF_continuous+Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage, data=data_na_omit)
plot.roc(rocobj_outcome1$CRF_continuous,
     legacy.axes = TRUE,
     main="ROC best threshold",
     thresholds="best", # to calculate optimal cut-off point
     print.thres="best") # to show the optimal cut-off value in the ROC curve

## ROC curve for the outcome of the composite of perioperative complications
rocobj_outcome2 <- pROC::roc(Composite_complications~CRF_continuous+Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage, data=data_na_omit)
plot.roc(rocobj_outcome2$CRF_continuous,
     legacy.axes = TRUE,
     main="ROC best threshold",
     thresholds="best", # to calculate optimal cut-off point
     print.thres="best") # to show the optimal cut-off value in the ROC curve

```


```{r}

##################################################################################################
# To transform variables to appropriate types for further analyses
##################################################################################################
data_na_omit$CRF_binary <- as.factor(data_na_omit$CRF_binary)
data_na_omit$Sex <- as.factor(data_na_omit$Sex)
data_na_omit$Smoking_ever <- as.factor(data_na_omit$Smoking_ever)
data_na_omit$Histology <- as.factor(data_na_omit$Histology)
data_na_omit$Clinical_stage <- as.factor(data_na_omit$Clinical_stage)
data_na_omit$Type_of_lung_resection <- as.factor(data_na_omit$Type_of_lung_resection)
data_na_omit$Hypertension <- as.factor(data_na_omit$Hypertension)
data_na_omit$Dyslipidemia <- as.factor(data_na_omit$Dyslipidemia)
data_na_omit$Diabetes  <- as.factor(data_na_omit$Diabetes)
data_na_omit$Coronary_artery_disease <- as.factor(data_na_omit$Coronary_artery_disease)

```



```{r}

##############################################################
# Propensity score overlap weighting
##############################################################
# References: 	
# Tianhui Zhou, Guangyu Tong, Fan Li, Laine Thomas, Fan Li (2022). PSweight: Propensity Score Weighting for Causal Inference with Observational Studies and Randomized Trials-Processing in R. R package version 1.1.8. https://cran.r-project.org/web/packages/PSweight
#	Thomas Lumley (2021). survey: Analysis of Complex Survey Samples-Processing in R. R package version 4.1-1. https://cran.r-project.org/web/packages/survey
# Kazuki YMortalityhida, Alexander Bartel, Jonathan J Chipman, Justin Bohn, Lucy DAgostino McGowan, Malcolm Barrett, Rune Haubo B Christensen, gbouzill (2022). tableone: Create 'Table 1' to Describe Baseline Characteristics with or without Propensity Score Weights-Processing in R. R package version 0.13.2. https://cran.r-project.org/web/packages/tableone
# Noah Greifer (2023). cobalt: Covariate Balance Tables and Plots-Processing in R. R package version 4.5.0. https://cran.r-project.org/web/packages/cobalt

# Step 1. To define the propensity score formula #
ps.formula<- CRF_binary~Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage

# Step 2. To define the outcome formula #
# Outcome 1: Mortality
out.formula_1<-Mortality~Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage

# Outcome 2: The composite of perioperative complications
out.formula_2<-Composite_complications~Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage

# Outcome 2.1: Technical-related complication
out.formula_2_1<-Technical_complication~Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage

# Outcome 2.2: Pulmonary complication
out.formula_2_2<-Pulmonary_complication~Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage

# Outcome 2.3: Cardiovascular complication
out.formula_2_3<-Cardiovascular_complication~Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage

# Step 3. To conduct propensity score weighting#
vars <- c("Sex","Age","BMI","Smoking_ever","Hypertension","Dyslipidemia","Diabetes","Coronary_artery_disease","Histology","Type_of_lung_resection","Clinical_stage")

# Outcome 1: Mortality
ow1<-PSweight(ps.formula = ps.formula,yname = 'Mortality',data = data_na_omit,weight = 'overlap')

# Outcome 2: The composite of perioperative complications
ow2<-PSweight(ps.formula = ps.formula,yname = 'Composite_complications',data = data_na_omit,weight = 'overlap')

# Outcome 2.1: Technical-related complication
ow2_1<-PSweight(ps.formula = ps.formula,yname = 'Technical_complication',data = data_na_omit,weight = 'overlap')

# Outcome 2.2: Pulmonary complication
ow2_2<-PSweight(ps.formula = ps.formula,yname = 'Pulmonary_complication',data = data_na_omit,weight = 'overlap')

# Outcome 2.3: Cardiovascular complication
ow2_3<-PSweight(ps.formula = ps.formula,yname = 'Cardiovascular_complication',data = data_na_omit,weight = 'overlap')

# Step 4: to append propensity score and weights
# Outcome 1: Mortality
ow1_outfit <- OUTmethod(out.formula = out.formula_1, family='binomial', datain = data_na_omit, dataout = data_na_omit)
ow1_est <- cbind(ow1_outfit$m.est, data_na_omit) 
names(ow1_est)[names(ow1_est) == 'ow1_outfit$m.est'] <- 'm_est'
ow1_est$ps_0 <- ow1$propensity[,1]
ow1_est$ps_1 <- ow1$propensity[,2]
ow1_est$psweights <- ifelse (ow1_est$CRF_binary==1, ow1_est$ps_0, ow1_est$ps_1)

# Outcome 2: The composite of perioperative complications
ow2_outfit <- OUTmethod(out.formula = out.formula_2, family='binomial', datain = data_na_omit, dataout = data_na_omit)
ow2_est <- cbind(ow2_outfit$m.est, data_na_omit) 
names(ow2_est)[names(ow2_est) == 'ow2_outfit$m.est'] <- 'm_est'
ow2_est$ps_0 <- ow2$propensity[,1]
ow2_est$ps_1 <- ow2$propensity[,2]
ow2_est$psweights <- ifelse (ow2_est$CRF_binary==1, ow2_est$ps_0, ow2_est$ps_1)

# Outcome 2.1: Technical-related complication
ow2_1_outfit <- OUTmethod(out.formula = out.formula_2_1, family='binomial', datain = data_na_omit, dataout = data_na_omit)
ow2_1_est <- cbind(ow2_1_outfit$m.est, data_na_omit) 
names(ow2_1_est)[names(ow2_1_est) == 'ow2_1_outfit$m.est'] <- 'm_est'
ow2_1_est$ps_0 <- ow2_1$propensity[,1]
ow2_1_est$ps_1 <- ow2_1$propensity[,2]
ow2_1_est$psweights <- ifelse (ow2_1_est$CRF_binary==1, ow2_1_est$ps_0, ow2_1_est$ps_1)

# Outcome 2.2: Pulmonary complication
ow2_2_outfit <- OUTmethod(out.formula = out.formula_2_2, family='binomial', datain = data_na_omit, dataout = data_na_omit)
ow2_2_est <- cbind(ow2_2_outfit$m.est, data_na_omit) 
names(ow2_2_est)[names(ow2_2_est) == 'ow2_2_outfit$m.est'] <- 'm_est'
ow2_2_est$ps_0 <- ow2_2$propensity[,1]
ow2_2_est$ps_1 <- ow2_2$propensity[,2]
ow2_2_est$psweightss <- ifelse (ow2_2_est$CRF_binary==1, ow2_2_est$ps_0, ow2_2_est$ps_1)

# Outcome 2.3: Cardiovascular complication
ow2_3_outfit <- OUTmethod(out.formula = out.formula_2_3, family='binomial', datain = data_na_omit, dataout = data_na_omit)
ow2_3_est <- cbind(ow2_3_outfit$m.est, data_na_omit) 
names(ow2_3_est)[names(ow2_3_est) == 'ow2_3_outfit$m.est'] <- 'm_est'
ow2_3_est$ps_0 <- ow2_3$propensity[,1]
ow2_3_est$ps_1 <- ow2_3$propensity[,2]
ow2_3_est$psweights <- ifelse (ow2_3_est$CRF_binary==1, ow2_3_est$ps_0, ow2_3_est$ps_1)

# Step 5: to output the distribution of covariates between the two groups before and after propensity score overlap weighting.
# to show the distribution of covariates before propensity score overlap weighting, with standardized mean differences between the two groups.
tabUnmatched <- CreateTableOne(vars = vars, strata = "CRF_binary", data = data_na_omit, test = FALSE)
print(tabUnmatched, smd = TRUE)
# to show the distribution of covariates after propensity score overlap weighting, with standardized mean differences between the two groups.
rhcSvy <- svydesign(ids = ~ 1, data = ow1_est, weights = ~ ow1_est$psweights)
tabWeighted <- svyCreateTableOne(vars = vars, strata = "CRF_binary", data = rhcSvy, test = FALSE)
print(tabWeighted, smd = TRUE)

#Step 6: to assess the balance in variables between the two groups by Love plot.
new.names <- c(Sex = "Sex",
               Age = "Age",
               BMI = "BMI",
               Smoking_ever = "Ever smoked",
               Hypertension = "Hypertension",
               Dyslipidemia = "Dyslipidemia",
               Diabetes = "Diabetes",
               Coronary_artery_disease = "Coronary artery disease",
               Histology_1 = "Adenocarcinoma",
               Histology_2 = "Squamouscell",
               Histology_3 = "Other NSCLCs",
               Type_of_lung_resection_1 = "Pneumonectomy",
               Type_of_lung_resection_2 = "Lobectomy",
               Type_of_lung_resection_3 = "Segmentectomy",
               Type_of_lung_resection_4 = "Wedgeresection",
               Type_of_lung_resection_5 = "Explorative thoracotomy without lung resection",
               Type_of_lung_resection_6 = "Two lung lobes resection",
               Clinical_stage_0 = "Clinical_stage 0",
               Clinical_stage_1 = "Clinical_stage I",
               Clinical_stage_2 = "Clinical_stage II",
               Clinical_stage_3 = "Clinical_stage IIIA"
)
love.plot(ps.formula, data = data_na_omit, abs = TRUE, weights = ow1_est$psweights,
          drop.distance = TRUE,
          thresholds = c(m = .1),
          var.names = new.names,
          line=TRUE,
          sample.names = c("Unweighted", "PS Weighted"),
          limits = c(0, .82),
          pMortalityition = c(.75, .25)) +
  theme(legend.box.background = element_rect(), 
        legend.box.margin = margin(1, 1, 1, 1))

ggsave("love.pdf", plot = last_plot(), device = "pdf", width = 8, height = 5)

```



```{r}

############################################################################################################################################################################
# To fit Cox proportional hazards models and calculate incidence rate difference between the groups, before and after incorporating weights derived from overlap weighting.
############################################################################################################################################################################
# References: 
# Terry M Therneau, Thomas Lumley, Atkinson Elizabeth, Crowson Cynthia (2023). survival: Survival Analysis-Processing in R. R package version 3.5-5. https://cran.r-project.org/web/packages/survival
# Minato Nakazawa (2023). fmsb: Functions for Medical Statistics Book with some Demographic Data-Processing in R. R package version 0.7.5. https://cran.r-project.org/web/packages/fmsb


## Outcome 1: Mortality ##
# Cox proportional hazards model before propensity score overlap weighting
cox_model_crude_ow1 <- coxph(formula=Surv(Mortality_time_to_event, Mortality) ~ CRF_binary,data=data_na_omit,method = "breslow",cluster=JMP_ID)
summary(cox_model_crude_ow1,extend=FALSE)

# Cox proportional hazards model after propensity score overlap weighting
cox_model_weighted_ow1 <- coxph(formula=Surv(Mortality_time_to_event, Mortality) ~ CRF_binary,data=data_na_omit,weights=ow1_est$psweights,method = "breslow",cluster=JMP_ID)
summary(cox_model_weighted_ow1,extend=FALSE)

# Incidence rate difference before propensity score overlap weighting
cox_model_pyears_ow1<- pyears(cox_model_crude_ow1,scale = 12) # 1 year = 12 months
summary(cox_model_pyears_ow1,rate=TRUE,ci.r=TRUE)
crude_IRD_ow1 <- ratedifference(cox_model_pyears_ow1$event[2], cox_model_pyears_ow1$event[1], cox_model_pyears_ow1$pyears[2], cox_model_pyears_ow1$pyears[1],CRC=TRUE,conf.level = 0.95)
crude_IRD_ow1$estimate*1000 # transform the unit from event per person-years to event per 1000 person-years
crude_IRD_ow1$conf.int*1000 # transform the unit from event per person-years to event per 1000 person-years
crude_IRD_ow1$p.value

# Incidence rate difference after propensity score overlap weighting
cox_model_weighted_pyears_ow1<- pyears(cox_model_weighted_ow1,scale = 12) # 1 year = 12 months
summary(cox_model_weighted_pyears_ow1,rate=TRUE,ci.r=TRUE)
weighted_IRD_ow1 <- ratedifference(cox_model_weighted_pyears_ow1$event[2], cox_model_weighted_pyears_ow1$event[1], cox_model_weighted_pyears_ow1$pyears[2], cox_model_weighted_pyears_ow1$pyears[1],CRC=TRUE,conf.level = 0.95)
weighted_IRD_ow1$estimate*1000 # transform the unit from event per person-years to event per 1000 person-years
weighted_IRD_ow1$conf.int*1000 # transform the unit from event per person-years to event per 1000 person-years
weighted_IRD_ow1$p.value

```




```{r}

############################################################################################################################################################################
# To fit logistic regression models, before and after incorporating weights derived from overlap weighting.
############################################################################################################################################################################
# Reference: 	Frank E Harrell Jr (2023). rms: Regression Modeling Strategies-Processing in R. R package version 6.6-0. https://cran.r-project.org/web/packages/rms.

## Outcome 2: the composite of perioperative complications ##
# Crude odds ratio
L <- glm(Composite_complications~CRF_binary, data = data_na_omit, maxit=10000)
L.est <- summary(L)$coefficients[2, 1]
L.se  <- summary(L)$coefficients[2, 2]
OR_est <- exp(L.est)
OR_lwr <- exp(L.est-1.96*L.se)
OR_upr <- exp(L.est+1.96*L.se)
OR_p   <- summary(L)$coefficients[2, 4]
OR_est
OR_lwr
OR_upr
OR_p 

# Weighted odds ratio
ow2_or    <- summary(ow2,    type = "OR", contrast = c(-1, 1), CI = TRUE)
ow2_or_est <- exp(ow2_or$estimates)[1,1]
ow2_or_est
ow2_or_est_lr <- exp(ow2_or$estimates)[1,4]
ow2_or_est_lr
ow2_or_est_ur <- exp(ow2_or$estimates)[1,5]
ow2_or_est_ur
ow2_or_est_pval <- ow2_or$estimates[1,6]
ow2_or_est_pval

## Outcome 2.1: technical-related complication ##
#Crude odds ratio
L <- glm(Technical_complication~CRF_binary, data = data_na_omit, maxit=10000)
L.est <- summary(L)$coefficients[2, 1]
L.se  <- summary(L)$coefficients[2, 2]
OR_est <- exp(L.est)
OR_lwr <- exp(L.est-1.96*L.se)
OR_upr <- exp(L.est+1.96*L.se)
OR_p   <- summary(L)$coefficients[2, 4]
OR_est
OR_lwr
OR_upr
OR_p 

# Weighted odds ratio
ow2_1_or    <- summary(ow2_1,    type = "OR", contrast = c(-1, 1), CI = TRUE)
ow2_1_or_est <- exp(ow2_1_or$estimates)[1,1]
ow2_1_or_est
ow2_1_or_est_lr <- exp(ow2_1_or$estimates)[1,4]
ow2_1_or_est_lr
ow2_1_or_est_ur <- exp(ow2_1_or$estimates)[1,5]
ow2_1_or_est_ur
ow2_1_or_est_pval <- ow2_1_or$estimates[1,6]
ow2_1_or_est_pval

## Outcome 2.2: pulmonary complication ##
# Crude odds ratio
L <- glm(Pulmonary_complication~CRF_binary, data = data_na_omit, maxit=10000)
L.est <- summary(L)$coefficients[2, 1]
L.se  <- summary(L)$coefficients[2, 2]
OR_est <- exp(L.est)
OR_lwr <- exp(L.est-1.96*L.se)
OR_upr <- exp(L.est+1.96*L.se)
OR_p   <- summary(L)$coefficients[2, 4]
OR_est
OR_lwr
OR_upr
OR_p 

# Weighted odds ratio
ow2_2_or    <- summary(ow2_2,    type = "OR", contrast = c(-1, 1), CI = TRUE)
ow2_2_or_est <-  exp(ow2_2_or$estimates)[1,1]
ow2_2_or_est
ow2_2_or_est_lr <- exp(ow2_2_or$estimates)[1,4]
ow2_2_or_est_lr
ow2_2_or_est_ur <- exp(ow2_2_or$estimates)[1,5]
ow2_2_or_est_ur
ow2_2_or_est_pval <- ow2_2_or$estimates[1,6]
ow2_2_or_est_pval

## Outcome 2.3: cardiovascular complication ##
# Crude odds ratio
L <- glm(Cardiovascular_complication~CRF_binary, data = data_na_omit, maxit=10000)
L.est <- summary(L)$coefficients[2, 1]
L.se  <- summary(L)$coefficients[2, 2]
OR_est <- exp(L.est)
OR_lwr <- exp(L.est-1.96*L.se)
OR_upr <- exp(L.est+1.96*L.se)
OR_p   <- summary(L)$coefficients[2, 4]
OR_est
OR_lwr
OR_upr
OR_p 

# Weighted odds ratio
ow2_3_or    <- summary(ow2_3,    type = "OR", contrast = c(-1, 1), CI = TRUE)
ow2_3_or_est <-  exp(ow2_3_or$estimates)[1,1]
ow2_3_or_est
ow2_3_or_est_lr <- exp(ow2_3_or$estimates)[1,4]
ow2_3_or_est_lr
ow2_3_or_est_ur <- exp(ow2_3_or$estimates)[1,5]
ow2_3_or_est_ur
ow2_3_or_est_pval <- ow2_3_or$estimates[1,6]
ow2_3_or_est_pval

```




```{r}

############################################################################################################################################################################
# To calculate complication rate and complication rate difference between groups.
############################################################################################################################################################################
# Reference: Minato Nakazawa (2023). fmsb: Functions for Medical Statistics Book with some Demographic Data-Processing in R. R package version 0.7.5. https://cran.r-project.org/web/packages/fmsb

## Perioperative complications ##
# To calculate number of participants in the exposed and unexposed groups
N_participants <- aggregate(x=data_na_omit$JMP_ID, by=list(data_na_omit$CRF_binary),length)
N_participants$x

# Outcome 2: the composite of Perioperative complications # 
# To calculate number of complications in the exposed and unexposed groups
N_complications_2<-aggregate(x=data_na_omit$Composite_complications, by=list(data_na_omit$CRF_binary),sum)
N_complications_2$x 
crude_IRD_ow2 <- ratedifference(59, 97, 234, 661,CRC=TRUE,conf.level = 0.95) 
crude_IRD_ow2$estimate*1000 
crude_IRD_ow2$conf.int*1000 
crude_IRD_ow2$p.value

# Weighted complication rate and complication rate difference
contrast_grp0 <- c(1,0)
contrast_grp1 <- c(0,1)
muhat  <- ow2$muhat
covmu  <- ow2$covmu
incidence_rate_calculation <- function(contrast,muhat,covmu){
  est.h<-c(contrast%*%muhat)
  se.h<-sqrt(diag(contrast%*%covmu%*%contrast))
  zval.h<-est.h/se.h
  lcl<-est.h-qnorm(0.975)*se.h
  ucl<-est.h+qnorm(0.975)*se.h
  p.value<-2*(1-pnorm(abs(est.h/se.h)))
  return(c(contrast%*%muhat,lcl,ucl))
}
incidence_rate_calculation(contrast_grp0,muhat=muhat,covmu=covmu)
incidence_rate_calculation(contrast_grp1,muhat=muhat,covmu=covmu)
ow2_dif    <- summary(ow2,    type = "DIF", contrast = c(-1, 1), CI = TRUE)
ow2_dif$estimates 

## Outcome 2.1: technical-related complication ##
# Crude complication rate difference
# To calculate number of exposed and unexposed cases
N_complications_2_1<-aggregate(x=data_na_omit$Technical_complication, by=list(data_na_omit$CRF_binary),sum)
N_complications_2_1$x 
crude_IRD_ow2_1 <- ratedifference(14, 60, 234, 661,CRC=TRUE,conf.level = 0.95) 
crude_IRD_ow2_1$estimate*1000 
crude_IRD_ow2_1$conf.int*1000 
crude_IRD_ow2_1$p.value

# Weighted complication rate and complication rate difference
contrast_grp0 <- c(1,0)
contrast_grp1 <- c(0,1)
muhat  <- ow2_1$muhat
covmu  <- ow2_1$covmu
incidence_rate_calculation <- function(contrast,muhat,covmu){
  est.h<-c(contrast%*%muhat)
  se.h<-sqrt(diag(contrast%*%covmu%*%contrast))
  zval.h<-est.h/se.h
  lcl<-est.h-qnorm(0.975)*se.h
  ucl<-est.h+qnorm(0.975)*se.h
  p.value<-2*(1-pnorm(abs(est.h/se.h)))
  return(c(contrast%*%muhat,lcl,ucl))
}
incidence_rate_calculation(contrast_grp0,muhat=muhat,covmu=covmu)
incidence_rate_calculation(contrast_grp1,muhat=muhat,covmu=covmu)
ow2_1_dif    <- summary(ow2_1,    type = "DIF", contrast = c(-1, 1), CI = TRUE)
ow2_1_dif$estimates 

## Outcome 2.2: pulmonary complication ##
# Crude complication rate difference
# To calculate number of exposed and unexposed cases
N_complications_2_2<-aggregate(x=data_na_omit$Pulmonary_complication, by=list(data_na_omit$CRF_binary),sum)
N_complications_2_2$x 
crude_IRD_ow2_2 <- ratedifference(23, 34, 234, 661,CRC=TRUE,conf.level = 0.95) 
crude_IRD_ow2_2$estimate*1000 
crude_IRD_ow2_2$conf.int*1000 
crude_IRD_ow2_2$p.value

# Weighted complication rate and complication rate difference
contrast_grp0 <- c(1,0)
contrast_grp1 <- c(0,1)
muhat  <- ow2_2$muhat
covmu  <- ow2_2$covmu
incidence_rate_calculation <- function(contrast,muhat,covmu){
  est.h<-c(contrast%*%muhat)
  se.h<-sqrt(diag(contrast%*%covmu%*%contrast))
  zval.h<-est.h/se.h
  lcl<-est.h-qnorm(0.975)*se.h
  ucl<-est.h+qnorm(0.975)*se.h
  p.value<-2*(1-pnorm(abs(est.h/se.h)))
  return(c(contrast%*%muhat,lcl,ucl))
}
incidence_rate_calculation(contrast_grp0,muhat=muhat,covmu=covmu)
incidence_rate_calculation(contrast_grp1,muhat=muhat,covmu=covmu)
ow2_2_dif    <- summary(ow2_2,    type = "DIF", contrast = c(-1, 1), CI = TRUE)
ow2_2_dif$estimates

## Outcome 2.3: cardiovascular complication##
# Crude complication rate difference
# To calculate number of exposed and unexposed cases
N_complications_2_3<-aggregate(x=data_na_omit$Cardiovascular_complication, by=list(data_na_omit$CRF_binary),sum)
N_complications_2_3$x
crude_IRD_ow2_3 <- ratedifference(15, 23, 234, 661,CRC=TRUE,conf.level = 0.95) 
crude_IRD_ow2_3$estimate*1000 
crude_IRD_ow2_3$conf.int*1000 
crude_IRD_ow2_3$p.value

# Weighted complication rate and complication rate difference
contrast_grp0 <- c(1,0)
contrast_grp1 <- c(0,1)
muhat  <- ow2_3$muhat
covmu  <- ow2_3$covmu
incidence_rate_calculation <- function(contrast,muhat,covmu){
  est.h<-c(contrast%*%muhat)
  se.h<-sqrt(diag(contrast%*%covmu%*%contrast))
  zval.h<-est.h/se.h
  lcl<-est.h-qnorm(0.975)*se.h
  ucl<-est.h+qnorm(0.975)*se.h
  p.value<-2*(1-pnorm(abs(est.h/se.h)))
  return(c(contrast%*%muhat,lcl,ucl))
}
incidence_rate_calculation(contrast_grp0,muhat=muhat,covmu=covmu)
incidence_rate_calculation(contrast_grp1,muhat=muhat,covmu=covmu)
ow2_3_dif    <- summary(ow2_3,    type = "DIF", contrast = c(-1, 1), CI = TRUE)
ow2_3_dif$estimates 

```



```{r}
############################################################################################################################################################################
# To calculate E-value
############################################################################################################################################################################
# Reference: Maya B. Mathur, Louisa H. Smith, Peng Ding, Tyler J. VanderWeele (2023). EValue: Sensitivity Analyses for Unmeasured Confounding and Other Biases in Observational Studies and Meta-Analyses-Processing in R. R package version 4.1.3. https://cran.r-project.org/web/packages/EValue

# E-Value for the outcome of mortality
evalues.HR(est = 1.98, lo = 1.31, hi = 2.98, rare = FALSE) # evalues.HR(est = the point estimate, lo = the lower limit of the confidence interval, hi = the higher limit of the confidence interval, rare = True if outcome is rare (<15 percent at end of follow-up); False if outcome is not rare (>15 percent at end of follow-up))

# E-Value for the outcome of the composite of complications
evalues.OR(est = 1.93, lo = 1.28, hi = 2.90, rare = FALSE) # evalues.HR(est = the point estimate, lo = the lower limit of the confidence interval, hi = the higher limit of the confidence interval, rare = True if outcome is rare (<15 percent at end of follow-up); False if outcome is not rare (>15 percent at end of follow-up))


```



```{r}
###########################################################
# Internal validation by Bootstrapping 
###########################################################
# Reference: Angelo Canty, Brian Ripley (2022). boot: Bootstrap Functions (Originally by Angelo Canty for S)-Processing in R. R package version 1.3-28.1. https://cran.r-project.org/web/packages/boot

## Outcome 1: Mortality ##
# To calculate C-index
boot.cox.Cindex.estimate.outcome1 <- function(data,indices) {
  samples <- data[indices, ]
  L <- lrm(formula=out.formula_1, data = samples, x=T, y=T, weights=ow1_est$psweights,maxit=10000)
  L$stats[6]
}
Cindex.boot.outcome1 <- boot(data_na_omit,boot.cox.Cindex.estimate.outcome1,R=1000) 
Cindex.boot.outcome1$t0
Cindex.boot.outcome1.se <- sd(Cindex.boot.outcome1$t)
Cindex.boot.outcome1_C_lower <- Cindex.boot.outcome1$t0-1.96*Cindex.boot.outcome1.se
Cindex.boot.outcome1_C_lower
Cindex.boot.outcome1_C_upper <- Cindex.boot.outcome1$t0+1.96*Cindex.boot.outcome1.se
Cindex.boot.outcome1_C_upper

# To calculate brier score
boot.cox.brier.estimate.outcome1 <- function(data,indices) {
  samples <- data[indices, ]
  L <- lrm(formula=out.formula_1, data = samples, x=T, y=T, weights=ow1_est$psweights,maxit=10000)
  L$stats[15]
}
brier.boot.outcome1 <- boot(data_na_omit,boot.cox.brier.estimate.outcome1,R=1000)
brier.boot.outcome1$t0
brier.boot.outcome1.se <- sd(brier.boot.outcome1$t)
brier.boot.outcome1_B_lower <- brier.boot.outcome1$t0-1.96*brier.boot.outcome1.se
brier.boot.outcome1_B_lower
brier.boot.outcome1_B_upper <- brier.boot.outcome1$t0+1.96*brier.boot.outcome1.se
brier.boot.outcome1_B_upper

# To obtain calibration slope
  L <- lrm(formula = out.formula_1, x = T, y = T,data=data_na_omit,weights = ow1_est$psweights)
  Slope <- vector()
  n <- nrow(data_na_omit)
  for(i in 1 : 1000) {
   g <- update(L, subset=sample(1 : n, n, replace=TRUE))
   v <- validate(g)
   Slope[i] <- v['Slope', 'index.corrected']
   Slope[i]
  }
  Slope.outcome1.CI <- quantile(Slope, c(.025, .975))
  Slope.outcome1.CI
  Slope.outcome1 <- mean(Slope)
  Slope.outcome1
  

## Outcome 2: The composite of perioperative complications ##
# To calculate C-index
boot.cox.Cindex.estimate.outcome2 <- function(data,indices) {
  samples <- data[indices, ]
  L <- lrm(formula=out.formula_2, data = samples, x=T, y=T, weights=ow2_est$psweights,maxit=10000)
  L$stats[6]
}
Cindex.boot.outcome2 <- boot(data_na_omit,boot.cox.Cindex.estimate.outcome2,R=1000) 
Cindex.boot.outcome2$t0
Cindex.boot.outcome2.se <- sd(Cindex.boot.outcome2$t)
Cindex.boot.outcome2_C_lower <- Cindex.boot.outcome2$t0-1.96*Cindex.boot.outcome2.se
Cindex.boot.outcome2_C_lower
Cindex.boot.outcome2_C_upper <- Cindex.boot.outcome2$t0+1.96*Cindex.boot.outcome2.se
Cindex.boot.outcome2_C_upper

# To calculate brier score
boot.cox.brier.estimate.outcome2 <- function(data,indices) {
  samples <- data[indices, ]
  L <- lrm(formula=out.formula_2, data = samples, x=T, y=T, weights=ow2_est$psweights,maxit=10000)
  L$stats[15]
}
brier.boot.outcome2 <- boot(data_na_omit,boot.cox.brier.estimate.outcome2,R=1000)
brier.boot.outcome2$t0
brier.boot.outcome2.se <- sd(brier.boot.outcome2$t)
brier.boot.outcome2_B_lower <- brier.boot.outcome2$t0-1.96*brier.boot.outcome2.se
brier.boot.outcome2_B_lower
brier.boot.outcome2_B_upper <- brier.boot.outcome2$t0+1.96*brier.boot.outcome2.se
brier.boot.outcome2_B_upper

# To obtain calibration slope
  L <- lrm(formula = out.formula_2, x = T, y = T,data=data_na_omit,weights = ow2_est$psweights)
  Slope <- vector()
  n <- nrow(data_na_omit)
  for(i in 1 : 1000) {
   g <- update(L, subset=sample(1 : n, n, replace=TRUE))
   v <- validate(g)
   Slope[i] <- v['Slope', 'index.corrected']
   Slope[i]
  }
  Slope.outcome2.CI <- quantile(Slope, c(.025, .975))
  Slope.outcome2.CI
  Slope.outcome2 <- mean(Slope)
  Slope.outcome2

```

```{r}
###########################################################
# Kaplan-Meier Survival Curves
###########################################################
# Reference: Alboukadel Kassambara, Marcin KMortalityinski, Przemyslaw Biecek, Scheipl Fabian (2021). survminer: Drawing Survival Curves using 'ggplot2'-processing in R. R version 0.4.9.https://cran.r-project.org/web/packages/survminer

## Crude_Mortality_KM ##
Crude_Mortality <- survfit(Surv(Mortality_time_to_event, Mortality) ~ CRF_binary,data=data_na_omit)

grid.draw.ggsurvplot <- function(x){
  survminer:::print.ggsurvplot(x, newpAge = FALSE)
}
Crude_Mortality_KM <- ggsurvplot(
  Crude_Mortality,                    
  pval = FALSE,         
  log.rank.weights="1",
  xlab = "Follow up time (years)",  
  ylab = "Overall survival (probability)",
  break.time.by = 12,    
  xscale = "m_y",
  risk.table = "absolute",  
  risk.table.y.text.col = TRUE,
  risk.table.y.text = FALSE,
  risk.table.Height = 0.3,
  legend.labs = 
    c("CRF ≥ 20 ml/kg/min", "CRF < 20 ml/kg/min"),  
  palette = 
    c("#2E9FDF", "#F08080"), 
  conf.int = T,
  surv.scale = c("percent"),
  xlim=c(0,60),
  legend = c(0.9,0.15),
  legend.title = "",
)
ggsave(file = "Crude_Mortality_KM.pdf", Crude_Mortality_KM, width = 16, height = 8.5, units = "in")

## Weighted_Mortality_KM ##
Weighted_Mortality <- survfit(Surv(Mortality_time_to_event, Mortality) ~ CRF_binary,data=data_na_omit,weights=ow1_est$psweights)

grid.draw.ggsurvplot <- function(x){
  survminer:::print.ggsurvplot(x, newpAge = FALSE)
}
Weighted_Mortality_KM <- ggsurvplot(
  Weighted_Mortality,                    
  pval = FALSE,         
  log.rank.weights="1",
  xlab = "Follow up time (years)",  
  ylab = "Overall survival (probability)",
  break.time.by = 12,   
  xscale = "m_y",
  risk.table = "absolute",  
  risk.table.y.text.col = TRUE,
  risk.table.y.text = FALSE,
  risk.table.Height = 0.3,
  legend.labs = 
    c("CRF ≥ 20 ml/kg/min", "CRF < 20 ml/kg/min"),  
  palette = 
    c("#2E9FDF", "#F08080"), 
  conf.int = T,
  surv.scale = c("percent"),
  xlim=c(0,60),
  legend = c(0.9,0.15),
  legend.title = "",
)
ggsave(file = "Weighted_Mortality_KM.pdf", Weighted_Mortality_KM, width = 16, height = 8.5, units = "in")


```


```{r}
#################################################
## Covariates Interaction tests ##
#################################################

###########################
## Outcome1：Mortality ##
###########################
# Run significant test for interaction terms - Sex
data_na_omit$Sex_num <- as.numeric(data_na_omit$Sex)
Outcome1_interaction_test_Sex<-Mortality~CRF_binary+Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage+Sex_num*CRF_binary
glm_interaction_test_Sex<-glm(Outcome1_interaction_test_Sex, data=data_na_omit, weight=ow1_est$psweights)
Outcome1_p_Sex <- coef(summary(glm_interaction_test_Sex))[,4]
Outcome1_p_Sex['CRF_binary1:Sex_num']

# Run significant test for interaction terms - Age
Outcome1_interaction_test_Age<-Mortality~CRF_binary+Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage+Age*CRF_binary
glm_interaction_test_Age<-glm(Outcome1_interaction_test_Age, data=data_na_omit, weight=ow1_est$psweights)
Outcome1_p_Age <- coef(summary(glm_interaction_test_Age))[,4]
Outcome1_p_Age['CRF_binary1:Age']

# Run significant test for interaction terms - BMI
Outcome1_interaction_test_BMI<-Mortality~CRF_binary+Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage+BMI*CRF_binary
glm_interaction_test_BMI<-glm(Outcome1_interaction_test_BMI, data=data_na_omit, weight=ow1_est$psweights)
Outcome1_p_BMI <- coef(summary(glm_interaction_test_BMI))[,4]
Outcome1_p_BMI['CRF_binary1:BMI']

# Run significant test for interaction terms - Smoking_ever
data_na_omit$Smoking_ever_num <- as.numeric(data_na_omit$Smoking_ever)
Outcome1_interaction_test_Smoking_ever<-Mortality~CRF_binary+Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage+Smoking_ever_num*CRF_binary
glm_interaction_test_Smoking_ever<-glm(Outcome1_interaction_test_Smoking_ever, data=data_na_omit, weight=ow1_est$psweights)
Outcome1_p_Smoking_ever <- coef(summary(glm_interaction_test_Smoking_ever))[,4]
Outcome1_p_Smoking_ever['CRF_binary1:Smoking_ever_num']

# Run significant test for interaction terms - Hypertension
data_na_omit$Hypertension_num <- as.numeric(data_na_omit$Hypertension)
Outcome1_interaction_test_Hypertension<-Mortality~CRF_binary+Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage+Hypertension_num*CRF_binary
glm_interaction_test_Hypertension<-glm(Outcome1_interaction_test_Hypertension, data=data_na_omit, weight=ow1_est$psweights)
Outcome1_p_Hypertension <- coef(summary(glm_interaction_test_Hypertension))[,4]
Outcome1_p_Hypertension['CRF_binary1:Hypertension_num']

# Run significant test for interaction terms - Dyslipidemia
data_na_omit$Dyslipidemia_num <- as.numeric(data_na_omit$Dyslipidemia)
Outcome1_interaction_test_Dyslipidemia<-Mortality~CRF_binary+Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage+Dyslipidemia_num*CRF_binary
glm_interaction_test_Dyslipidemia<-glm(Outcome1_interaction_test_Dyslipidemia, data=data_na_omit, weight=ow1_est$psweights)
Outcome1_p_Dyslipidemia<- coef(summary(glm_interaction_test_Dyslipidemia))[,4]
Outcome1_p_Dyslipidemia['CRF_binary1:Dyslipidemia_num']

# Run significant test for interaction terms - Diabetes
data_na_omit$Diabetes_num <- as.numeric(data_na_omit$Diabetes)
Outcome1_interaction_test_Diabetes<-Mortality~CRF_binary+Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage+Diabetes_num*CRF_binary
glm_interaction_test_Diabetes<-glm(Outcome1_interaction_test_Diabetes, data=data_na_omit, weight=ow1_est$psweights)
Outcome1_p_Diabetes<- coef(summary(glm_interaction_test_Diabetes))[,4]
Outcome1_p_Diabetes['CRF_binary1:Diabetes_num']

# Run significant test for interaction terms - Coronary_artery_disease
data_na_omit$Coronary_artery_disease_num <- as.numeric(data_na_omit$Coronary_artery_disease)
Outcome1_interaction_test_Coronary_artery_disease<-Mortality~CRF_binary+Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage+Coronary_artery_disease_num*CRF_binary
glm_interaction_test_Coronary_artery_disease<-glm(Outcome1_interaction_test_Coronary_artery_disease, data=data_na_omit, weight=ow1_est$psweights)
Outcome1_p_Coronary_artery_disease<- coef(summary(glm_interaction_test_Coronary_artery_disease))[,4]
Outcome1_p_Coronary_artery_disease['CRF_binary1:Coronary_artery_disease_num']

# Run significant test for interaction terms - Histology
data_na_omit$Histology_num <- as.numeric(data_na_omit$Histology)
Outcome1_interaction_test_Histology<-Mortality~CRF_binary+Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage+Histology_num*CRF_binary
glm_interaction_test_Histology<-glm(Outcome1_interaction_test_Histology, data=data_na_omit, weight=ow1_est$psweights)
Outcome1_p_Histology<- coef(summary(glm_interaction_test_Histology))[,4]
Outcome1_p_Histology['CRF_binary1:Histology_num']

# Run significant test for interaction terms - Type_of_lung_resection
data_na_omit$Type_of_lung_resection_num <- as.numeric(data_na_omit$Type_of_lung_resection)
Outcome1_interaction_test_Type_of_lung_resection<-Mortality~CRF_binary+Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage+Type_of_lung_resection_num*CRF_binary
glm_interaction_test_Type_of_lung_resection<-glm(Outcome1_interaction_test_Type_of_lung_resection, data=data_na_omit, weight=ow1_est$psweights)
Outcome1_p_Type_of_lung_resection<- coef(summary(glm_interaction_test_Type_of_lung_resection))[,4]
Outcome1_p_Type_of_lung_resection['CRF_binary1:Type_of_lung_resection_num']

# Run significant test for interaction terms - Clinical_stage
data_na_omit$Clinical_stage_num <- as.numeric(data_na_omit$Clinical_stage)
Outcome1_interaction_test_Clinical_stage<-Mortality~CRF_binary+Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage+Clinical_stage_num*CRF_binary
glm_interaction_test_Clinical_stage<-glm(Outcome1_interaction_test_Clinical_stage, data=data_na_omit, weight=ow1_est$psweights)
Outcome1_p_Clinical_stage<- coef(summary(glm_interaction_test_Clinical_stage))[,4]
Outcome1_p_Clinical_stage['CRF_binary1:Clinical_stage_num']


#################################################
## Outcome 2：the composite of complications ##
#################################################
data_na_omit$Sex_num <- as.numeric(data_na_omit$Sex)
Outcome2_interaction_test_Sex<-Composite_complications~CRF_binary+Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage+Sex_num*CRF_binary
glm_interaction_test_Sex<-glm(Outcome2_interaction_test_Sex, data=data_na_omit, weight=ow2_est$psweights)
Outcome2_p_Sex <- coef(summary(glm_interaction_test_Sex))[,4]
Outcome2_p_Sex['CRF_binary1:Sex_num']

# Run significant test for interaction terms - Age
Outcome2_interaction_test_Age<-Composite_complications~CRF_binary+Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage+Age*CRF_binary
glm_interaction_test_Age<-glm(Outcome2_interaction_test_Age, data=data_na_omit, weight=ow2_est$psweights)
Outcome2_p_Age <- coef(summary(glm_interaction_test_Age))[,4]
Outcome2_p_Age['CRF_binary1:Age']

# Run significant test for interaction terms - BMI
Outcome2_interaction_test_BMI<-Composite_complications~CRF_binary+Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage+BMI*CRF_binary
glm_interaction_test_BMI<-glm(Outcome2_interaction_test_BMI, data=data_na_omit, weight=ow2_est$psweights)
Outcome2_p_BMI <- coef(summary(glm_interaction_test_BMI))[,4]
Outcome2_p_BMI['CRF_binary1:BMI']

# Run significant test for interaction terms - Smoking_ever
data_na_omit$Smoking_ever_num <- as.numeric(data_na_omit$Smoking_ever)
Outcome2_interaction_test_Smoking_ever<-Composite_complications~CRF_binary+Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage+Smoking_ever_num*CRF_binary
glm_interaction_test_Smoking_ever<-glm(Outcome2_interaction_test_Smoking_ever, data=data_na_omit, weight=ow2_est$psweights)
Outcome2_p_Smoking_ever <- coef(summary(glm_interaction_test_Smoking_ever))[,4]
Outcome2_p_Smoking_ever['CRF_binary1:Smoking_ever_num']

# Run significant test for interaction terms - Hypertension
data_na_omit$Hypertension_num <- as.numeric(data_na_omit$Hypertension)
Outcome2_interaction_test_Hypertension<-Composite_complications~CRF_binary+Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage+Hypertension_num*CRF_binary
glm_interaction_test_Hypertension<-glm(Outcome2_interaction_test_Hypertension, data=data_na_omit, weight=ow2_est$psweights)
Outcome2_p_Hypertension <- coef(summary(glm_interaction_test_Hypertension))[,4]
Outcome2_p_Hypertension['CRF_binary1:Hypertension_num']

# Run significant test for interaction terms - Dyslipidemia
data_na_omit$Dyslipidemia_num <- as.numeric(data_na_omit$Dyslipidemia)
Outcome2_interaction_test_Dyslipidemia<-Composite_complications~CRF_binary+Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage+Dyslipidemia_num*CRF_binary
glm_interaction_test_Dyslipidemia<-glm(Outcome2_interaction_test_Dyslipidemia, data=data_na_omit, weight=ow2_est$psweights)
Outcome2_p_Dyslipidemia<- coef(summary(glm_interaction_test_Dyslipidemia))[,4]
Outcome2_p_Dyslipidemia['CRF_binary1:Dyslipidemia_num']

# Run significant test for interaction terms - Diabetes
data_na_omit$Diabetes_num <- as.numeric(data_na_omit$Diabetes)
Outcome2_interaction_test_Diabetes<-Composite_complications~CRF_binary+Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage+Diabetes_num*CRF_binary
glm_interaction_test_Diabetes<-glm(Outcome2_interaction_test_Diabetes, data=data_na_omit, weight=ow2_est$psweights)
Outcome2_p_Diabetes<- coef(summary(glm_interaction_test_Diabetes))[,4]
Outcome2_p_Diabetes['CRF_binary1:Diabetes_num']

# Run significant test for interaction terms - Coronary_artery_disease
data_na_omit$Coronary_artery_disease_num <- as.numeric(data_na_omit$Coronary_artery_disease)
Outcome2_interaction_test_Coronary_artery_disease<-Composite_complications~CRF_binary+Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage+Coronary_artery_disease_num*CRF_binary
glm_interaction_test_Coronary_artery_disease<-glm(Outcome2_interaction_test_Coronary_artery_disease, data=data_na_omit, weight=ow2_est$psweights)
Outcome2_p_Coronary_artery_disease<- coef(summary(glm_interaction_test_Coronary_artery_disease))[,4]
Outcome2_p_Coronary_artery_disease['CRF_binary1:Coronary_artery_disease_num']

# Run significant test for interaction terms - Histology
data_na_omit$Histology_num <- as.numeric(data_na_omit$Histology)
Outcome2_interaction_test_Histology<-Composite_complications~CRF_binary+Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage+Histology_num*CRF_binary
glm_interaction_test_Histology<-glm(Outcome2_interaction_test_Histology, data=data_na_omit, weight=ow2_est$psweights)
Outcome2_p_Histology<- coef(summary(glm_interaction_test_Histology))[,4]
Outcome2_p_Histology['CRF_binary1:Histology_num']

# Run significant test for interaction terms - Type_of_lung_resection
data_na_omit$Type_of_lung_resection_num <- as.numeric(data_na_omit$Type_of_lung_resection)
Outcome2_interaction_test_Type_of_lung_resection<-Composite_complications~CRF_binary+Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage+Type_of_lung_resection_num*CRF_binary
glm_interaction_test_Type_of_lung_resection<-glm(Outcome2_interaction_test_Type_of_lung_resection, data=data_na_omit, weight=ow2_est$psweights)
Outcome2_p_Type_of_lung_resection<- coef(summary(glm_interaction_test_Type_of_lung_resection))[,4]
Outcome2_p_Type_of_lung_resection['CRF_binary1:Type_of_lung_resection_num']

# Run significant test for interaction terms - Clinical_stage
data_na_omit$Clinical_stage_num <- as.numeric(data_na_omit$Clinical_stage)
Outcome2_interaction_test_Clinical_stage<-Composite_complications~CRF_binary+Sex+Age+BMI+Smoking_ever+Hypertension+Dyslipidemia+Diabetes+Coronary_artery_disease+Histology+Type_of_lung_resection+Clinical_stage+Clinical_stage_num*CRF_binary
glm_interaction_test_Clinical_stage<-glm(Outcome2_interaction_test_Clinical_stage, data=data_na_omit, weight=ow2_est$psweights)
Outcome2_p_Clinical_stage<- coef(summary(glm_interaction_test_Clinical_stage))[,4]
Outcome2_p_Clinical_stage['CRF_binary1:Clinical_stage_num']

```

```{r}

##############################################################
# Subgroup analysis
##############################################################

# The study involved conducting pre-specified subgroup analyses based on birth-sex,age, body mass index, and smoking history. In order to ensure consistency, overlap weighting propensity scores were re-created prior to subgroup model development, and all other analyses followed the same process outlined above. Due to the length of the analysis, the codes utilized in these processes were not repeated in this section for brevity.

```
